# Adicione apenas as seções e chaves que você quer modificar.
# O Grafana usará o padrão para o resto.

# Esse plugin é necessário para o Zabbix
[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource